#' Simulated MAF Data
#'
#' An example dataset generated by the function generate_maf_data(), with n_sample = 20 and n_genes = 50.
#'
#' @format A list with two entries:
#' \describe{
#'   \item{maf}{An annotated mutation dataframe with 3 columns and 1007 rows: \describe{
#'     \item{Tumor_Sample_Barcode}{A sample id for each mutation.}
#'     \item{Hugo_Symbol}{The name of the gene location for each mutation.}
#'     \item{Variant_Classification}{The mutation type for each mutation.}}}
#'   \item{gene_lengths}{A data frame with two rows: \describe{
#'     \item{Hugo_Symbol}{The name of each gene.}
#'     \item{max_cds}{The length of each gene, as defined by maximum coding sequence.}}}
#' }
"example_maf_data"

#' Simulated MAF Data
#'
#' An example dataset generated by the function generate_maf_data(), with n_sample = 20 and n_genes = 50.
#'
#' @format A list with three entries:
#' \describe{
#'   \item{train}{An object 'train'.}
#'   \item{val}{An object 'val'.}
#'   \item{test}{An object 'test'.}
#' }
#' Each of these three objects is a list with the following entries (for more detail see the documentation for the function get_table_from_maf()):
#' \describe{
#'   \item{matrix}{A sparse matrix of mutations.}
#'   \item{sample_list}{A character vector of sample IDs, corresponding to the rows of the mutation matrix.}
#'   \item{gene_list}{A characer vector of gene names.}
#'   \item{mut_types_list}{A character vector of mutation types.}
#'   \item{colnames}{A character vector of gene name/mutation type combinations (in each case separated by the character "_"), corresponding to the columns of the mutation matrix.}
#' }
"example_tables"
